version: "3"

volumes:
  media_volume:

services:
  blog:
    build: blog
    environment:
      - DB_NAME=blog_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SECRET=django-insecure-sdkj@phb6a(-5pd*#fmg)!0s!i08(u5g4+)_k0pf91^&mt_0%c
    command: bash -c "
      sleep 4 &&
      python manage.py collectstatic --no-input &&
      python manage.py migrate &&
      gunicorn -b 0.0.0.0:8000 config.wsgi"
    volumes:
      - media_volume:/media/
    depends_on:
      - db

  db:
    build:
      context: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blog_db
    ports:
      - 5432:5432

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - media_volume:/media/:ro
    ports:
      - 80:80
    depends_on:
      - blog
    restart: on-failure